관리자 front-end
volume-catcher/license-service pull request #8
Opened 2022-09-13 07:22 UTC by seungseunglee

2022-09-16 02:38 UTC, seh9306 requested changes
수고하셨어요! 리뷰가 늦었네요 ㅎㅎ.. 

DB쪽은 아무래도 저도 이제 JPA 공부하고 있어서 리뷰가 부족하니 이해해주세요!

- license_product 테이블 명칭을 계약 (Contract)로 변경
 제품과 라이선스로 파생된 테이블로 고객이 결제하면 계약이 발생하는 개념으로 생각했는데 어떤지 한 번 생각해보세요!

2022-09-16 02:38 UTC, seh9306 commented on license-service/src/main/java/com/teamdev/licenseservice/controller/ProductController.java
> +    @GetMapping("/license/{licenseKey}")
REST API는 명사에 복수형을 기본으로 권장하고 있어요.

ex) 
api/v1/licenses -> 전체 라이선스 조회
api/v1/licenses/{licenseKey} -> 특정 라이선스 조회
api/v1/products/licenses/{licenceKey}

그리고 이 API는 지금 현재보다는 api/v1/licenses/{licenseKey}/products로 하는건 어떨까요?

2022-09-16 02:38 UTC, seh9306 commented on license-service/src/main/java/com/teamdev/licenseservice/service/LicenseService.java
> +        return licenseRepository.findAll().stream().map(LicenseKeyDto::from).collect(Collectors.toList());
전체 데이터를 조회하지 말고 페이징처리를 해보세요! 다른 api도 동일합니다. 

PageRequest

2022-09-16 02:38 UTC, seh9306 commented on license-service/src/main/java/com/teamdev/licenseservice/repository/LicenseProductRepositoryImpl.java
> +    private QLicenseProduct licenseProduct = QLicenseProduct.licenseProduct;
해당 변수는 static final 로 선언되어 있으니,

```java
import static com.teamdev.licenseservice.entity.QLicenseProduct.licenseProduct;
```

로 처리하는건 어떠세요?

intellij에서 static 변수는 bold체로 표기해서 구분하기 쉽습니다.

2022-09-16 02:38 UTC, seh9306 commented on license-service/src/main/java/com/teamdev/licenseservice/controller/LicenseProductController.java
> +    public List<LicenseProductNumDto> getLicenseProductsNum() {
API의 의미가 애매해요.

라이선스 도메인에 있는게 더 적합할거 같아요. 현재 프로젝트에서는 라이선스 전체 조회라는 개념은 정말 라이선스 테이블만 조회하는게 아니고 등록, 만료된 제품의 카운트도 포함된다고 생각해보세요!

2022-09-16 04:39 UTC, seungseunglee commented on license-service/src/main/java/com/teamdev/licenseservice/repository/LicenseProductRepositoryImpl.java
> +    private QLicenseProduct licenseProduct = QLicenseProduct.licenseProduct;
아!! 좋은 것 같습니다. 그러면 같은 클래스의 아래 함수에 선언한 QLicense와 QProduct도 import static으로 수정할까요? 아니면 두 클래스는 특정 함수에서만 사용되므로 그냥 두는 게 나을까요?

```java
    @Override
    public LicenseProduct findOneLicenseProductByLicenseKeyAndProductNameQ(String licenseKey, String productName) {
        QLicense license = QLicense.license;  // <<
        QProduct product = QProduct.product; // <<

        return ...;
    }
```

2022-09-16 04:40 UTC, seungseunglee commented on license-service/src/main/java/com/teamdev/licenseservice/service/LicenseService.java
> +        return licenseRepository.findAll().stream().map(LicenseKeyDto::from).collect(Collectors.toList());
넵 알겠습니다!

2022-09-16 05:30 UTC, seh9306 commented on license-service/src/main/java/com/teamdev/licenseservice/service/LicenseService.java
> +        Optional<Account> account = accountRepository.findById(licenseDto.getAccountId());
Optional을 사용하는 경우

```java
return accountRepository.findById(licenseDto.getAccountId())
                .map(account -> {
                    License license = License.builder()
                            .key(licenseDto.getKey())
                            .account(account)
                            .build();
                    return licenseRepository.save(license);
                })
                .orElseThrow(() -> new NotFoundException(ErrorMessage.ACCOUNT_NOT_FOUND));
```

이렇게 처리할 수 있어요.

2022-09-16 05:38 UTC, seh9306 commented on license-service/src/main/java/com/teamdev/licenseservice/repository/LicenseProductRepositoryImpl.java
> +    private QLicenseProduct licenseProduct = QLicenseProduct.licenseProduct;
Q 클래스를 직접 다 써주거나 위와 같은 이유로 import하는게 좋다고 봐요.

근데 저는 불필요하게 길어지는 코드를 안좋아해서 개인적으로는 import가 좋다고봐요. intellij에서 bold 형식으로 표기를 안해준다면 Q 클래스를 쓰는 방향으로 한 번 고민해볼거 같아요.

2022-09-16 06:36 UTC, seungseunglee commented on license-service/src/main/java/com/teamdev/licenseservice/controller/ProductController.java
> +    @GetMapping("/license/{licenseKey}")
아!! 이 API를 어디에 두는 게 좋을지 확신이 안 서서 고민했었는데 LicenseController에 두는 게 더 자연스럽겠네요! 감사합니다.

2022-09-16 07:03 UTC, seungseunglee commented on license-service/src/main/java/com/teamdev/licenseservice/controller/LicenseProductController.java
> +    public List<LicenseProductNumDto> getLicenseProductsNum() {
수정했습니다. 그러면 기존의 라이선스 이름만 가져오던 API 는 제거하는 게 좋을까요??

2022-09-16 07:20 UTC, seungseunglee commented on license-service/src/main/java/com/teamdev/licenseservice/service/LicenseService.java
> +        Optional<Account> account = accountRepository.findById(licenseDto.getAccountId());
map이 Optional에도 되는 줄 몰랐어요!! 감사합니다.

2022-09-16 08:12 UTC, seh9306 commented on license-service/src/main/java/com/teamdev/licenseservice/controller/LicenseProductController.java
> +    public List<LicenseProductNumDto> getLicenseProductsNum() {
GET /api/v1/licenses를 대체한다라고 생각하시면 되요.

뷰 관점에서 라이선스를 조회하면 그 응답에는 당연히 등록된 제품과 만료된 제품 수가 포함될거라고 기대할거에요. 그런데 api 가 GET api/v1/license-product/num 를 이용해야한다면 직관적이지 못하고, count만 조회하는 api라고 오해할 수 있을거에요.

2022-09-17 12:39 UTC, seungseunglee commented on license-service/src/main/java/com/teamdev/licenseservice/controller/LicenseProductController.java
> +    public List<LicenseProductNumDto> getLicenseProductsNum() {
> 수정했습니다. 그러면 기존의 라이선스 이름만 조회하는 API 는 제거하는 게 좋을까요??

기존의 라이선스 이름만 조회하는 API는 제거.
기존의 라이선스 이름만 조회하는 API를 등록, 만료된 제품의 카운트도 포함하는 API로 완전히 변경.

2022-09-18 17:00 UTC, seungseunglee commented on license-service/src/main/java/com/teamdev/licenseservice/repository/LicenseProductRepositoryImpl.java
> +    private QLicenseProduct licenseProduct = QLicenseProduct.licenseProduct;
말씀하신 Q 클래스를 쓰는 게
```java
private QLicenseProduct licenseProduct = QLicenseProduct.licenseProduct;
```
이렇게 정의하는 거 말씀하시는 건가요??

2022-09-19 05:03 UTC, seh9306 commented on license-service/src/main/java/com/teamdev/licenseservice/repository/LicenseProductRepositoryImpl.java
> +    private QLicenseProduct licenseProduct = QLicenseProduct.licenseProduct;
QLicenseProduct.licenseProduct를 직접 다 코드에 표기해서 데이터를 담는 객체를 쓰는게 아니고, 테이블 칼럼 표현을 위한 변수로 사용한다는 느낌을 주겠다는거였어요.

2022-09-19 05:04 UTC, seh9306 approved these changes

2022-09-19 05:06 UTC, merged

2022-09-19 05:50 UTC, seungseunglee commented on license-service/src/main/java/com/teamdev/licenseservice/repository/LicenseProductRepositoryImpl.java
> +    private QLicenseProduct licenseProduct = QLicenseProduct.licenseProduct;
> QLicenseProduct.licenseProduct를 직접 다 코드에 표기해서 데이터를 담는 객체를 쓰는게 아니고, 테이블 칼럼 표현을 위한 변수로 사용한다는 느낌을 주겠다는거였어요.

Q 클래스는 데이터를 담는 객체가 아닌, 테이블의 칼럼을 의미하므로 표현 방식에서 칼럼임을 나타내었으면 한다.

- 예시
```java
QLicenseProduct qLicenseProduct = QLicenseProduct.licenseProduct;
select(qLicenseProduct)
.from(qLicenseProduct)
```
또는 
```java
select(QLicenseProduct.licenseProduct)
.from(QLicenseProduct.licenseProduct)
```